export enum WeaponType {
  TivaraSlingshot = "TivaraSlingshot",
  OrcBoomerang = "OrcBoomerang",
  SkaduweeBow = "SkaduweeBow",
  SkeletonBow = "SkeletonBow",
  FrostSpell = "FrostSpell",
  FireSpell = "FireSpell",
  Tivara = "TivaraMace",
  SkaduweeAxe = "SkaduweeAxe",
  SkeletonScythe = "SkeletonScythe",
  SkeletonSword = "SkeletonSword",
  OrcSword = "OrcSword",
  PirateScimitar = "PirateScimitar",
  CyclopsHalberd = "CyclopsHalberd",
  GeneralWarriorSpear = "GeneralWarriorSpear",
  CenturionSpear = "CenturionSpear",
  SkaduweeMagicianStaff = "SkaduweeMagicianStaff",
  WorkerHands = "WorkerHands",
  MummyHands = "MummyHands",
  SkeletonHands = "SkeletonHands",
  ZombieHands = "ZombieHands",
  ZombieLargeHands = "ZombieLargeHands",
  MinotaurHands = "MinotaurHands",
  Furball = "Furball",
  AlchemistVase = "AlchemistVase",
  BowTower = "BowTower",
  WolfBite = "WolfBite"
}
