drop table if exists messages;
create table messages
(
  id               bigint generated by default as identity primary key,
  created_at       timestamp with time zone default now() not null,
  text             text                                   not null,
  user_id          uuid                                   not null,
  game_instance_id text                                   null
);

-- add a foreign key constraint to the auth.users table
ALTER TABLE messages
  ADD CONSTRAINT messages_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES profiles(id);

-- add index on created_at for efficient pagination queries
create index messages_created_at_idx on messages (created_at desc);

-- add index on game_instance_id for efficient filtering
create index messages_game_instance_id_idx on messages (game_instance_id) where game_instance_id is not null;

drop policy if exists "Enable read access for all users" on messages;
-- CREATE POLICY "Enable read access for all users" ON "public"."messages"
-- AS PERMISSIVE FOR SELECT
-- TO authenticated
-- USING (true)

drop policy if exists "Enable select for users based on user_id" on messages;
CREATE POLICY "Enable select for users based on user_id" ON "public"."messages"
  AS PERMISSIVE FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

drop policy if exists "Enable read access for all users" on messages;
CREATE POLICY "Enable insert for service_role only" ON "public"."messages"
  AS PERMISSIVE FOR INSERT
  TO service_role
  WITH CHECK (true);

drop policy if exists "Enable select for service_role" on messages;
CREATE POLICY "Enable select for service_role" ON "public"."messages"
  AS PERMISSIVE FOR SELECT
  TO service_role
  USING (true);

-- enable row level security
alter table messages
  enable row level security;
