// The constants with the animation keys.
// GENERATED BY PHASER EDITOR AND MANUALLY TRANSFERRED TO SRC

export const ANIM_HEDGEHOG_IDLE_RIGHT = "hedgehog_idle_right";

export const ANIM_HEDGEHOG_IDLE_BOTTOM = "hedgehog_idle_bottom";

export const ANIM_HEDGEHOG_IDLE_TOP = "hedgehog_idle_top";

export const ANIM_HEDGEHOG_WALK_RIGHT = "hedgehog_walk_right";

export const ANIM_HEDGEHOG_WALK_TOP = "hedgehog_walk_top";

export const ANIM_HEDGEHOG_BALL_RIGHT = "hedgehog_ball_right";

export const ANIM_HEDGEHOG_BALL_DOWN = "hedgehog_ball_down";

export const ANIM_HEDGEHOG_BALL_TOP = "hedgehog_ball_top";

export const ANIM_HEDGEHOG_IDLE_LEFT = "hedgehog_idle_left";

export const ANIM_HEDGEHOG_WALK_LEFT = "hedgehog_walk_left";

export const ANIM_HEDGEHOG_BALL_LEFT = "hedgehog_ball_left";
