// The constants with the animation keys.
// GENERATED BY PHASER EDITOR AND MANUALLY TRANSFERRED TO SRC

import { AnimationDefinitionMap, AnimationType } from "../entity/actor/components/animation-actor-component";
import {
  ANIM_HEDGEHOG_BALL_DOWN,
  ANIM_HEDGEHOG_BALL_LEFT,
  ANIM_HEDGEHOG_BALL_RIGHT,
  ANIM_HEDGEHOG_BALL_TOP,
  ANIM_HEDGEHOG_IDLE_DOWN,
  ANIM_HEDGEHOG_IDLE_LEFT,
  ANIM_HEDGEHOG_IDLE_RIGHT,
  ANIM_HEDGEHOG_IDLE_TOP,
  ANIM_HEDGEHOG_WALK_DOWN,
  ANIM_HEDGEHOG_WALK_LEFT,
  ANIM_HEDGEHOG_WALK_RIGHT,
  ANIM_HEDGEHOG_WALK_TOP,
  ANIM_SHEEP_DOWN_WALK,
  ANIM_SHEEP_IDLE_DOWN,
  ANIM_SHEEP_IDLE_DOWN_SHEARED,
  ANIM_SHEEP_IDLE_LEFT,
  ANIM_SHEEP_IDLE_LEFT_SHEARED,
  ANIM_SHEEP_IDLE_RIGHT,
  ANIM_SHEEP_IDLE_RIGHT_SHEARED,
  ANIM_SHEEP_IDLE_UP,
  ANIM_SHEEP_IDLE_UP_SHEARED,
  ANIM_SHEEP_LEFT_WALK,
  ANIM_SHEEP_RIGHT_WALK,
  ANIM_SHEEP_UP_WALK
} from "../prefabs/animals/anims/animals";

export const ANIM_SHEEP_DEFINITION: AnimationDefinitionMap = {
  [AnimationType.Idle]: {
    north: { key: ANIM_SHEEP_IDLE_UP },
    south: { key: ANIM_SHEEP_IDLE_DOWN },
    west: { key: ANIM_SHEEP_IDLE_LEFT },
    east: { key: ANIM_SHEEP_IDLE_RIGHT }
  },
  ["sheared"]: {
    north: { key: ANIM_SHEEP_IDLE_UP_SHEARED },
    south: { key: ANIM_SHEEP_IDLE_DOWN_SHEARED },
    west: { key: ANIM_SHEEP_IDLE_LEFT_SHEARED },
    east: { key: ANIM_SHEEP_IDLE_RIGHT_SHEARED }
  },
  [AnimationType.Walk]: {
    north: { key: ANIM_SHEEP_UP_WALK },
    south: { key: ANIM_SHEEP_DOWN_WALK },
    west: { key: ANIM_SHEEP_LEFT_WALK },
    east: { key: ANIM_SHEEP_RIGHT_WALK }
  }
};
export const ANIM_HEDGEHOG_DEFINITION: AnimationDefinitionMap = {
  [AnimationType.Idle]: {
    north: { key: ANIM_HEDGEHOG_IDLE_TOP },
    south: { key: ANIM_HEDGEHOG_IDLE_DOWN },
    west: { key: ANIM_HEDGEHOG_IDLE_LEFT },
    east: { key: ANIM_HEDGEHOG_IDLE_RIGHT }
  },
  [AnimationType.Walk]: {
    north: { key: ANIM_HEDGEHOG_WALK_TOP },
    south: { key: ANIM_HEDGEHOG_WALK_DOWN },
    west: { key: ANIM_HEDGEHOG_WALK_LEFT },
    east: { key: ANIM_HEDGEHOG_WALK_RIGHT }
  },
  ["ball"]: {
    north: { key: ANIM_HEDGEHOG_BALL_TOP },
    south: { key: ANIM_HEDGEHOG_BALL_DOWN },
    west: { key: ANIM_HEDGEHOG_BALL_LEFT },
    east: { key: ANIM_HEDGEHOG_BALL_RIGHT }
  }
};
