// The constants with the animation keys.
// GENERATED BY PHASER EDITOR AND MANUALLY TRANSFERRED TO SRC
export const ANIM_BLOOD_SPLATTER_SMALL_1 = "blood_splatter_small_1";

export const ANIM_BLOOD_SPLATTER_SMALL_2 = "blood_splatter_small_2";

export const ANIM_BLOOD_SPLATTER_SMALL_3 = "blood_splatter_small_3";

export const ANIM_BLOOD_SPLATTER_SMALL_4 = "blood_splatter_small_4";

export const ANIM_BLOOD_SPLATTER_SMALL_5 = "blood_splatter_small_5";

export const ANIM_IMPACT_0 = "impact_0";

export const ANIM_IMPACT_1 = "impact_1";

export const ANIM_IMPACT_2 = "impact_2";

export const ANIM_IMPACT_3 = "impact_3";

export const ANIM_IMPACT_4 = "impact_4";

export const ANIM_IMPACT_5 = "impact_5";

export const ANIM_IMPACT_6 = "impact_6";

export const ANIM_IMPACT_7 = "impact_7";

export const ANIM_IMPACT_8 = "impact_8";

export const ANIM_IMPACT_9 = "impact_9";

export const ANIM_IMPACT_10 = "impact_10";

export const ANIM_IMPACT_11 = "impact_11";

export const ANIM_IMPACT_12 = "impact_12";

export const ANIM_IMPACT_13 = "impact_13";

export const ANIM_IMPACT_14 = "impact_14";

export const ANIM_IMPACT_15 = "impact_15";

export const ANIM_IMPACT_16 = "impact_16";

export const ANIM_IMPACT_17 = "impact_17";

export const ANIM_IMPACT_18 = "impact_18";

export const ANIM_IMPACT_19 = "impact_19";

export const ANIM_IMPACT_20 = "impact_20";

export const ANIM_IMPACT_21 = "impact_21";

export const ANIM_IMPACT_22 = "impact_22";

export const ANIM_IMPACT_23 = "impact_23";
