// The constants with the animation keys.
// GENERATED BY PHASER EDITOR AND MANUALLY TRANSFERRED TO SRC
export const ANIM_SKADUWEE_BUILDINGS_INFANTRY_INN_ENTRANCE = "skaduwee-buildings-infantry-inn-entrance";
export const ANIM_SKADUWEE_BUILDINGS_OWLERY_OWL = "skaduwee-buildings-owlery-owl";
export const ANIM_SKADUWEE_BUILDINGS_OWLERY_OWL_FLAP = "skaduwee-buildings-owlery-owl-flap";
export const ANIM_FROST_FORGE_FLAME = "frost_forge_flame";
