// The constants with the animation keys.
// GENERATED BY PHASER EDITOR AND MANUALLY TRANSFERRED TO SRC
export const ANIM_TIVARA_BUILDINGS_OLIVAL_SMALL = "tivara-buildings-olival-small";

export const ANIM_TIVARA_BUILDINGS_AKNGUARD_FLAME = "tivara-buildings-aknguard-flame";

export const ANIM_TIVARA_BUILDINGS_ANKGUARD_FLAME_STICK = "tivara-buildings-ankguard-flame-stick";

export const ANIM_TIVARA_BUILDINGS_ANKGUARD_FLAG = "tivara-buildings-ankguard-flag";
