export enum AnimationType {
  Idle = "Idle",
  Run = "Run",
  Walk = "Walk",
  Shoot = "Shoot",
  Build = "Build",
  Chop = "Chop",
  Mine = "Mine",
  Dig = "Dig",
  Harvest = "Harvest",
  Repair = "Repair",
  Heal = "Heal",
  Cast = "Cast",
  Death = "Death",
  Damage = "Damage",
  Slash = "Slash",
  InvertedSlash = "InvertedSlash",
  Smash = "Smash",
  Thrust = "Thrust",
  LargeSlash = "LargeSlash",
  LargeThrust = "largeThrust"
}
