export enum AnimationType {
  Idle = "idle",
  Run = "run",
  Walk = "walk",
  Shoot = "shoot",
  Build = "build",
  Chop = "chop",
  Mine = "mine",
  Dig = "dig",
  Harvest = "Harvest",
  Repair = "repair",
  Heal = "heal",
  Cast = "cast",
  Death = "death",
  Slash = "slash",
  InvertedSlash = "invertedSlash",
  Smash = "smash",
  Thrust = "thrust",
  LargeSlash = "largeSlash",
  LargeThrust = "largeThrust"
}
