// This file was generated from "convert-to-enums.js" script
export enum TivaraWorkerMaleSfx {
  ATTACK_1 = "Attack 1",
  ATTACK_2 = "Attack 2",
  ATTACK_3 = "Attack 3",
  BUILD_1 = "Build 1",
  BUILD_2 = "Build 2",
  CHOP_1 = "Chop 1",
  CHOP_2 = "Chop 2",
  DAMAGE1 = "Damage1",
  DAMAGE2 = "Damage2",
  DAMAGE3 = "Damage3",
  DEATH_1 = "Death 1",
  DEATH_2 = "Death 2",
  DEATH1 = "Death1",
  DEATH2 = "Death2",
  DEATH3 = "Death3",
  ENTER_BUILDING_1 = "Enter building 1",
  ENTER_BUILDING_2 = "Enter building 2",
  LOCATION_UNAVAILABLE_1 = "Location unavailable 1",
  LOCATION_UNAVAILABLE_2 = "Location unavailable 2",
  MINE_2 = "Mine 2",
  MOVE_1 = "Move 1",
  MOVE_2 = "Move 2",
  MOVE_3 = "Move 3",
  MOVE_4 = "Move 4",
  REPAIR_1 = "Repair 1",
  REPAIR_2 = "Repair 2",
  SELECTION_1 = "Selection 1",
  SELECTION_2 = "Selection 2",
  SELECTION_3 = "Selection 3",
  SELECTION_4 = "Selection 4",
  SELECTION_EXTRA_1 = "Selection Extra 1"
}
