// This file was generated from "convert-to-enums.js" script
export enum TivaraWorkerFemaleSfx {
  ATTACK_1 = "Attack 1",
  ATTACK_2 = "Attack 2",
  ATTACK_3 = "Attack 3",
  BUILD_1 = "Build 1",
  BUILD_2 = "Build 2",
  CHOP_1 = "Chop 1",
  CHOP_2 = "Chop 2",
  DAMAGE_1 = "Damage 1",
  DAMAGE_2 = "Damage 2",
  DAMAGE_3 = "Damage 3",
  DAMAGE_4 = "Damage 4",
  DAMAGE_5 = "Damage 5",
  DAMAGE_6 = "Damage 6",
  ENTER_BUILDING_1_2 = "Enter building 1-2",
  ENTER_BUILDING_1 = "Enter building 1",
  LOCATION_UNAVAILABLE_1 = "Location unavailable 1",
  LOCATION_UNAVAILABLE_2 = "Location unavailable 2",
  MINE_1 = "Mine 1",
  MINE_2 = "Mine 2",
  MOVE_1 = "Move 1",
  MOVE_2 = "Move 2",
  MOVE_3 = "Move 3",
  MOVE_4 = "Move 4",
  REPAIR_1 = "Repair 1",
  REPAIR_2 = "Repair 2",
  SELECTION_1 = "Selection 1",
  SELECTION_2 = "Selection 2",
  SELECTION_3 = "Selection 3",
  SELECTION_4 = "Selection 4"
}
