create sequence "public"."fly_squasher_scores_id_seq";

create sequence "public"."little_muncher_scores_id_seq";

create sequence "public"."probable_waffle_achievements_id_seq";

create sequence "public"."probable_waffle_player_score_metrics_id_seq";

create sequence "public"."probable_waffle_player_scores_id_seq";

create sequence "public"."probable_waffle_score_metric_types_id_seq";

create sequence "public"."probable_waffle_score_snapshots_id_seq";


  create table "public"."fly_squasher_scores" (
    "id" integer not null default nextval('public.fly_squasher_scores_id_seq'::regclass),
    "score" integer not null,
    "level" integer not null,
    "user_id" uuid not null,
    "date" timestamp without time zone default CURRENT_TIMESTAMP
      );


alter table "public"."fly_squasher_scores" enable row level security;


  create table "public"."little_muncher_scores" (
    "id" integer not null default nextval('public.little_muncher_scores_id_seq'::regclass),
    "score" integer not null,
    "hill" integer not null,
    "user_id" uuid not null,
    "date" timestamp without time zone default CURRENT_TIMESTAMP
      );


alter table "public"."little_muncher_scores" enable row level security;


  create table "public"."messages" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "text" text not null,
    "user_id" uuid not null,
    "game_instance_id" uuid
      );


alter table "public"."messages" enable row level security;


  create table "public"."probable_waffle_achievements" (
    "id" integer not null default nextval('public.probable_waffle_achievements_id_seq'::regclass),
    "achievement_id" character varying(50) not null,
    "user_id" uuid not null,
    "unlocked_date" timestamp without time zone default CURRENT_TIMESTAMP,
    "metadata" jsonb
      );


alter table "public"."probable_waffle_achievements" enable row level security;


  create table "public"."probable_waffle_game_sessions" (
    "id" uuid not null default gen_random_uuid(),
    "game_instance_id" uuid not null,
    "game_type" text not null,
    "map_id" integer not null,
    "session_state" text not null,
    "started_at" timestamp with time zone not null default now(),
    "ended_at" timestamp with time zone,
    "total_duration_seconds" integer,
    "created_by_user_id" uuid not null,
    "scores_submitted" boolean not null default false,
    "scores_submitted_by" uuid,
    "scores_submitted_at" timestamp with time zone,
    "human_player_count" integer not null default 1,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."probable_waffle_game_sessions" enable row level security;


  create table "public"."probable_waffle_player_score_metrics" (
    "id" bigint not null default nextval('public.probable_waffle_player_score_metrics_id_seq'::regclass),
    "player_score_id" bigint not null,
    "metric_type_id" integer not null,
    "metric_value" bigint not null default 0,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."probable_waffle_player_score_metrics" enable row level security;


  create table "public"."probable_waffle_player_scores" (
    "id" bigint not null default nextval('public.probable_waffle_player_scores_id_seq'::regclass),
    "game_session_id" uuid not null,
    "user_id" uuid,
    "player_number" integer not null,
    "player_name" text not null,
    "player_type" text not null,
    "team_number" integer,
    "faction_type" text not null,
    "game_result" text not null,
    "eliminated" boolean not null default false,
    "eliminated_at" timestamp with time zone,
    "final_score" integer not null default 0,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."probable_waffle_player_scores" enable row level security;


  create table "public"."probable_waffle_score_metric_types" (
    "id" integer not null default nextval('public.probable_waffle_score_metric_types_id_seq'::regclass),
    "metric_key" text not null,
    "metric_name" text not null,
    "metric_category" text not null,
    "description" text,
    "display_order" integer not null default 0,
    "is_active" boolean not null default true,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."probable_waffle_score_metric_types" enable row level security;


  create table "public"."probable_waffle_score_snapshots" (
    "id" bigint not null default nextval('public.probable_waffle_score_snapshots_id_seq'::regclass),
    "game_session_id" uuid not null,
    "snapshots" jsonb not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."probable_waffle_score_snapshots" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "name" text,
    "profile_image_url" text,
    "email" text
      );


alter table "public"."profiles" enable row level security;

alter sequence "public"."fly_squasher_scores_id_seq" owned by "public"."fly_squasher_scores"."id";

alter sequence "public"."little_muncher_scores_id_seq" owned by "public"."little_muncher_scores"."id";

alter sequence "public"."probable_waffle_achievements_id_seq" owned by "public"."probable_waffle_achievements"."id";

alter sequence "public"."probable_waffle_player_score_metrics_id_seq" owned by "public"."probable_waffle_player_score_metrics"."id";

alter sequence "public"."probable_waffle_player_scores_id_seq" owned by "public"."probable_waffle_player_scores"."id";

alter sequence "public"."probable_waffle_score_metric_types_id_seq" owned by "public"."probable_waffle_score_metric_types"."id";

alter sequence "public"."probable_waffle_score_snapshots_id_seq" owned by "public"."probable_waffle_score_snapshots"."id";

CREATE UNIQUE INDEX fly_squasher_scores_pkey ON public.fly_squasher_scores USING btree (id);

CREATE INDEX fly_squasher_scores_user_id_idx ON public.fly_squasher_scores USING btree (user_id);

CREATE UNIQUE INDEX little_muncher_scores_pkey ON public.little_muncher_scores USING btree (id);

CREATE INDEX little_muncher_scores_user_id_idx ON public.little_muncher_scores USING btree (user_id);

CREATE UNIQUE INDEX messages_pkey ON public.messages USING btree (id);

CREATE INDEX messages_user_id_idx ON public.messages USING btree (user_id);

CREATE UNIQUE INDEX probable_waffle_achievements_pkey ON public.probable_waffle_achievements USING btree (id);

CREATE UNIQUE INDEX probable_waffle_achievements_user_achievement_unique ON public.probable_waffle_achievements USING btree (user_id, achievement_id);

CREATE INDEX probable_waffle_game_sessions_created_by_user_id_idx ON public.probable_waffle_game_sessions USING btree (created_by_user_id);

CREATE UNIQUE INDEX probable_waffle_game_sessions_game_instance_id_key ON public.probable_waffle_game_sessions USING btree (game_instance_id);

CREATE UNIQUE INDEX probable_waffle_game_sessions_pkey ON public.probable_waffle_game_sessions USING btree (id);

CREATE INDEX probable_waffle_game_sessions_scores_submitted_by_idx ON public.probable_waffle_game_sessions USING btree (scores_submitted_by) WHERE (scores_submitted_by IS NOT NULL);

CREATE INDEX probable_waffle_player_score_metrics_metric_type_id_idx ON public.probable_waffle_player_score_metrics USING btree (metric_type_id);

CREATE UNIQUE INDEX probable_waffle_player_score_metrics_pkey ON public.probable_waffle_player_score_metrics USING btree (id);

CREATE UNIQUE INDEX probable_waffle_player_score_metrics_unique_idx ON public.probable_waffle_player_score_metrics USING btree (player_score_id, metric_type_id);

CREATE UNIQUE INDEX probable_waffle_player_scores_pkey ON public.probable_waffle_player_scores USING btree (id);

CREATE UNIQUE INDEX probable_waffle_player_scores_session_player_idx ON public.probable_waffle_player_scores USING btree (game_session_id, player_number);

CREATE INDEX probable_waffle_player_scores_user_id_idx ON public.probable_waffle_player_scores USING btree (user_id) WHERE (user_id IS NOT NULL);

CREATE UNIQUE INDEX probable_waffle_score_metric_types_metric_key_key ON public.probable_waffle_score_metric_types USING btree (metric_key);

CREATE UNIQUE INDEX probable_waffle_score_metric_types_pkey ON public.probable_waffle_score_metric_types USING btree (id);

CREATE UNIQUE INDEX probable_waffle_score_snapshots_game_session_id_idx ON public.probable_waffle_score_snapshots USING btree (game_session_id);

CREATE UNIQUE INDEX probable_waffle_score_snapshots_pkey ON public.probable_waffle_score_snapshots USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

alter table "public"."fly_squasher_scores" add constraint "fly_squasher_scores_pkey" PRIMARY KEY using index "fly_squasher_scores_pkey";

alter table "public"."little_muncher_scores" add constraint "little_muncher_scores_pkey" PRIMARY KEY using index "little_muncher_scores_pkey";

alter table "public"."messages" add constraint "messages_pkey" PRIMARY KEY using index "messages_pkey";

alter table "public"."probable_waffle_achievements" add constraint "probable_waffle_achievements_pkey" PRIMARY KEY using index "probable_waffle_achievements_pkey";

alter table "public"."probable_waffle_game_sessions" add constraint "probable_waffle_game_sessions_pkey" PRIMARY KEY using index "probable_waffle_game_sessions_pkey";

alter table "public"."probable_waffle_player_score_metrics" add constraint "probable_waffle_player_score_metrics_pkey" PRIMARY KEY using index "probable_waffle_player_score_metrics_pkey";

alter table "public"."probable_waffle_player_scores" add constraint "probable_waffle_player_scores_pkey" PRIMARY KEY using index "probable_waffle_player_scores_pkey";

alter table "public"."probable_waffle_score_metric_types" add constraint "probable_waffle_score_metric_types_pkey" PRIMARY KEY using index "probable_waffle_score_metric_types_pkey";

alter table "public"."probable_waffle_score_snapshots" add constraint "probable_waffle_score_snapshots_pkey" PRIMARY KEY using index "probable_waffle_score_snapshots_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."fly_squasher_scores" add constraint "fly_squasher_scores_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."fly_squasher_scores" validate constraint "fly_squasher_scores_user_id_fkey";

alter table "public"."little_muncher_scores" add constraint "little_muncher_scores_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."little_muncher_scores" validate constraint "little_muncher_scores_user_id_fkey";

alter table "public"."messages" add constraint "messages_game_instance_id_fkey" FOREIGN KEY (game_instance_id) REFERENCES public.probable_waffle_game_sessions(game_instance_id) ON DELETE SET NULL not valid;

alter table "public"."messages" validate constraint "messages_game_instance_id_fkey";

alter table "public"."messages" add constraint "messages_profile_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) not valid;

alter table "public"."messages" validate constraint "messages_profile_id_fkey";

alter table "public"."probable_waffle_achievements" add constraint "probable_waffle_achievements_user_achievement_unique" UNIQUE using index "probable_waffle_achievements_user_achievement_unique";

alter table "public"."probable_waffle_achievements" add constraint "probable_waffle_achievements_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."probable_waffle_achievements" validate constraint "probable_waffle_achievements_user_id_fkey";

alter table "public"."probable_waffle_game_sessions" add constraint "probable_waffle_game_sessions_created_by_user_id_fkey" FOREIGN KEY (created_by_user_id) REFERENCES public.profiles(id) not valid;

alter table "public"."probable_waffle_game_sessions" validate constraint "probable_waffle_game_sessions_created_by_user_id_fkey";

alter table "public"."probable_waffle_game_sessions" add constraint "probable_waffle_game_sessions_game_instance_id_key" UNIQUE using index "probable_waffle_game_sessions_game_instance_id_key";

alter table "public"."probable_waffle_game_sessions" add constraint "probable_waffle_game_sessions_scores_submitted_by_fkey" FOREIGN KEY (scores_submitted_by) REFERENCES public.profiles(id) not valid;

alter table "public"."probable_waffle_game_sessions" validate constraint "probable_waffle_game_sessions_scores_submitted_by_fkey";

alter table "public"."probable_waffle_player_score_metrics" add constraint "probable_waffle_player_score_metrics_metric_type_id_fkey" FOREIGN KEY (metric_type_id) REFERENCES public.probable_waffle_score_metric_types(id) not valid;

alter table "public"."probable_waffle_player_score_metrics" validate constraint "probable_waffle_player_score_metrics_metric_type_id_fkey";

alter table "public"."probable_waffle_player_score_metrics" add constraint "probable_waffle_player_score_metrics_player_score_id_fkey" FOREIGN KEY (player_score_id) REFERENCES public.probable_waffle_player_scores(id) ON DELETE CASCADE not valid;

alter table "public"."probable_waffle_player_score_metrics" validate constraint "probable_waffle_player_score_metrics_player_score_id_fkey";

alter table "public"."probable_waffle_player_scores" add constraint "probable_waffle_player_scores_game_session_id_fkey" FOREIGN KEY (game_session_id) REFERENCES public.probable_waffle_game_sessions(id) ON DELETE CASCADE not valid;

alter table "public"."probable_waffle_player_scores" validate constraint "probable_waffle_player_scores_game_session_id_fkey";

alter table "public"."probable_waffle_player_scores" add constraint "probable_waffle_player_scores_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) not valid;

alter table "public"."probable_waffle_player_scores" validate constraint "probable_waffle_player_scores_user_id_fkey";

alter table "public"."probable_waffle_score_metric_types" add constraint "probable_waffle_score_metric_types_metric_key_key" UNIQUE using index "probable_waffle_score_metric_types_metric_key_key";

alter table "public"."probable_waffle_score_snapshots" add constraint "probable_waffle_score_snapshots_game_session_id_fkey" FOREIGN KEY (game_session_id) REFERENCES public.probable_waffle_game_sessions(id) ON DELETE CASCADE not valid;

alter table "public"."probable_waffle_score_snapshots" validate constraint "probable_waffle_score_snapshots_game_session_id_fkey";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

set check_function_bodies = off;

create or replace view "public"."fly_squasher_scores_with_user_meta" with (security_invoker=on) as  WITH scores AS (
         SELECT fss.id,
            fss.score,
            fss.level,
            fss.user_id,
            fss.date,
            pr.name,
            row_number() OVER (PARTITION BY fss.level ORDER BY fss.score DESC) AS level_rn
           FROM (( SELECT fly_squasher_scores.id,
                    fly_squasher_scores.score,
                    fly_squasher_scores.level,
                    fly_squasher_scores.user_id,
                    fly_squasher_scores.date,
                    dense_rank() OVER (PARTITION BY fly_squasher_scores.level, fly_squasher_scores.user_id ORDER BY fly_squasher_scores.score DESC) AS rn
                   FROM public.fly_squasher_scores) fss
             JOIN public.profiles pr ON ((fss.user_id = pr.id)))
          WHERE (fss.rn = 1)
        )
 SELECT id,
    score,
    level,
    user_id,
    date,
    name,
    level_rn
   FROM scores
  WHERE (level_rn <= 3);


CREATE OR REPLACE FUNCTION public.get_player_score_metrics(p_player_score_id bigint)
 RETURNS jsonb
 LANGUAGE sql
 STABLE
AS $function$
SELECT jsonb_object_agg(mt.metric_key, m.metric_value)
FROM probable_waffle_player_score_metrics m
       JOIN probable_waffle_score_metric_types mt ON m.metric_type_id = mt.id
WHERE m.player_score_id = p_player_score_id;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
BEGIN

  -- if provider is Google
  IF NEW.raw_app_meta_data ->> 'provider' = 'google' THEN
    INSERT INTO public.profiles (id, email, name, profile_image_url, created)
    VALUES (NEW.id, NEW.email, NEW.raw_user_meta_data ->> 'name', NEW.raw_user_meta_data ->> 'avatar_url', CURRENT_TIMESTAMP);
  ELSE
    -- else insert random name
    INSERT INTO public.profiles (id, email, name, profile_image_url, created)
    VALUES (NEW.id,
            NEW.email,
            substring(
              string_agg(chr(65 + floor(random() * 26)::int), ''), -- Random letters (A-Z)
              1, 10 -- 10-character random name
            ),
            '',
            CURRENT_TIMESTAMP);
  END IF;

  RETURN NEW;
END;
$function$
;

create or replace view "public"."little_muncher_scores_with_user_meta" with (security_invoker=on) as  WITH ranked_scores AS (
         SELECT s.id,
            s.score,
            s.hill,
            s.user_id,
            s.date,
            p.name AS user_name,
            row_number() OVER (PARTITION BY s.hill, s.user_id ORDER BY s.score DESC) AS user_rn
           FROM (public.little_muncher_scores s
             JOIN public.profiles p ON ((s.user_id = p.id)))
        ), unique_user_scores AS (
         SELECT ranked_scores.id,
            ranked_scores.score,
            ranked_scores.hill,
            ranked_scores.user_id,
            ranked_scores.date,
            ranked_scores.user_name,
            ranked_scores.user_rn
           FROM ranked_scores
          WHERE (ranked_scores.user_rn = 1)
        ), hill_ranked AS (
         SELECT unique_user_scores.id,
            unique_user_scores.score,
            unique_user_scores.hill,
            unique_user_scores.user_id,
            unique_user_scores.user_name,
            unique_user_scores.date,
            row_number() OVER (PARTITION BY unique_user_scores.hill ORDER BY unique_user_scores.score DESC) AS hill_rn
           FROM unique_user_scores
        )
 SELECT id,
    score,
    hill,
    user_id,
    user_name,
    date
   FROM hill_ranked
  WHERE (hill_rn <= 3)
  ORDER BY hill, hill_rn;


create or replace view "public"."probable_waffle_match_history" with (security_invoker=on) as  SELECT gs.id,
    gs.game_instance_id,
    gs.game_type,
    gs.map_id,
    gs.session_state,
    gs.started_at,
    gs.ended_at,
    gs.total_duration_seconds,
    gs.scores_submitted,
    gs.human_player_count,
    creator.name AS created_by_name,
    submitter.name AS submitted_by_name,
    ( SELECT json_agg(json_build_object('player_number', ps.player_number, 'player_name', ps.player_name, 'player_type', ps.player_type, 'faction_type', ps.faction_type, 'game_result', ps.game_result, 'final_score', ps.final_score, 'is_current_user', (ps.user_id = auth.uid())) ORDER BY ps.final_score DESC) AS json_agg
           FROM public.probable_waffle_player_scores ps
          WHERE (ps.game_session_id = gs.id)) AS players,
    (EXISTS ( SELECT 1
           FROM public.probable_waffle_player_scores ps
          WHERE ((ps.game_session_id = gs.id) AND (ps.user_id = auth.uid())))) AS user_participated,
    ( SELECT ps.game_result
           FROM public.probable_waffle_player_scores ps
          WHERE ((ps.game_session_id = gs.id) AND (ps.user_id = auth.uid()))
         LIMIT 1) AS user_result
   FROM ((public.probable_waffle_game_sessions gs
     LEFT JOIN public.profiles creator ON ((gs.created_by_user_id = creator.id)))
     LEFT JOIN public.profiles submitter ON ((gs.scores_submitted_by = submitter.id)))
  WHERE ((gs.scores_submitted = true) AND (EXISTS ( SELECT 1
           FROM public.probable_waffle_player_scores ps
          WHERE ((ps.game_session_id = gs.id) AND (ps.user_id = auth.uid())))))
  ORDER BY gs.ended_at DESC NULLS LAST, gs.started_at DESC;


create materialized view "public"."probable_waffle_player_scores_full" as  SELECT ps.id,
    ps.game_session_id,
    ps.user_id,
    ps.player_number,
    ps.player_name,
    ps.player_type,
    ps.team_number,
    ps.faction_type,
    ps.game_result,
    ps.eliminated,
    ps.eliminated_at,
    ps.final_score,
    ps.created_at,
    max(
        CASE
            WHEN (mt.metric_key = 'units_produced'::text) THEN m.metric_value
            ELSE (0)::bigint
        END) AS units_produced,
    max(
        CASE
            WHEN (mt.metric_key = 'units_killed'::text) THEN m.metric_value
            ELSE (0)::bigint
        END) AS units_killed,
    max(
        CASE
            WHEN (mt.metric_key = 'units_lost'::text) THEN m.metric_value
            ELSE (0)::bigint
        END) AS units_lost,
    max(
        CASE
            WHEN (mt.metric_key = 'buildings_constructed'::text) THEN m.metric_value
            ELSE (0)::bigint
        END) AS buildings_constructed,
    max(
        CASE
            WHEN (mt.metric_key = 'buildings_destroyed'::text) THEN m.metric_value
            ELSE (0)::bigint
        END) AS buildings_destroyed,
    max(
        CASE
            WHEN (mt.metric_key = 'buildings_lost'::text) THEN m.metric_value
            ELSE (0)::bigint
        END) AS buildings_lost,
    max(
        CASE
            WHEN (mt.metric_key = 'resources_collected_minerals'::text) THEN m.metric_value
            ELSE (0)::bigint
        END) AS resources_collected_minerals,
    max(
        CASE
            WHEN (mt.metric_key = 'resources_collected_stone'::text) THEN m.metric_value
            ELSE (0)::bigint
        END) AS resources_collected_stone,
    max(
        CASE
            WHEN (mt.metric_key = 'resources_collected_wood'::text) THEN m.metric_value
            ELSE (0)::bigint
        END) AS resources_collected_wood,
    max(
        CASE
            WHEN (mt.metric_key = 'resources_spent_minerals'::text) THEN m.metric_value
            ELSE (0)::bigint
        END) AS resources_spent_minerals,
    max(
        CASE
            WHEN (mt.metric_key = 'resources_spent_stone'::text) THEN m.metric_value
            ELSE (0)::bigint
        END) AS resources_spent_stone,
    max(
        CASE
            WHEN (mt.metric_key = 'resources_spent_wood'::text) THEN m.metric_value
            ELSE (0)::bigint
        END) AS resources_spent_wood,
    max(
        CASE
            WHEN (mt.metric_key = 'final_resources_minerals'::text) THEN m.metric_value
            ELSE (0)::bigint
        END) AS final_resources_minerals,
    max(
        CASE
            WHEN (mt.metric_key = 'final_resources_stone'::text) THEN m.metric_value
            ELSE (0)::bigint
        END) AS final_resources_stone,
    max(
        CASE
            WHEN (mt.metric_key = 'final_resources_wood'::text) THEN m.metric_value
            ELSE (0)::bigint
        END) AS final_resources_wood,
    max(
        CASE
            WHEN (mt.metric_key = 'damage_dealt'::text) THEN m.metric_value
            ELSE (0)::bigint
        END) AS damage_dealt,
    max(
        CASE
            WHEN (mt.metric_key = 'damage_received'::text) THEN m.metric_value
            ELSE (0)::bigint
        END) AS damage_received,
    max(
        CASE
            WHEN (mt.metric_key = 'healing_done'::text) THEN m.metric_value
            ELSE (0)::bigint
        END) AS healing_done,
    max(
        CASE
            WHEN (mt.metric_key = 'max_army_size'::text) THEN m.metric_value
            ELSE (0)::bigint
        END) AS max_army_size,
    max(
        CASE
            WHEN (mt.metric_key = 'max_building_count'::text) THEN m.metric_value
            ELSE (0)::bigint
        END) AS max_building_count
   FROM ((public.probable_waffle_player_scores ps
     LEFT JOIN public.probable_waffle_player_score_metrics m ON ((ps.id = m.player_score_id)))
     LEFT JOIN public.probable_waffle_score_metric_types mt ON ((m.metric_type_id = mt.id)))
  GROUP BY ps.id, ps.game_session_id, ps.user_id, ps.player_number, ps.player_name, ps.player_type, ps.team_number, ps.faction_type, ps.game_result, ps.eliminated, ps.eliminated_at, ps.final_score, ps.created_at;


create or replace view "public"."probable_waffle_player_stats" with (security_invoker=on) as  SELECT ps.user_id,
    p.name AS player_name,
    count(*) AS total_games,
    count(*) FILTER (WHERE (ps.game_result = 'win'::text)) AS wins,
    count(*) FILTER (WHERE (ps.game_result = 'loss'::text)) AS losses,
    count(*) FILTER (WHERE (ps.game_result = 'tie'::text)) AS ties,
    round((((count(*) FILTER (WHERE (ps.game_result = 'win'::text)))::numeric / (NULLIF(count(*) FILTER (WHERE (ps.game_result <> 'quit'::text)), 0))::numeric) * (100)::numeric), 2) AS win_rate_percentage,
    sum(ps.units_produced) AS total_units_produced,
    sum(ps.units_killed) AS total_units_killed,
    sum(ps.buildings_constructed) AS total_buildings_constructed,
    sum(ps.buildings_destroyed) AS total_buildings_destroyed,
    (avg(ps.final_score))::integer AS avg_final_score,
    max(ps.final_score) AS max_final_score
   FROM (public.probable_waffle_player_scores_full ps
     LEFT JOIN public.profiles p ON ((ps.user_id = p.id)))
  WHERE (ps.user_id IS NOT NULL)
  GROUP BY ps.user_id, p.name;


CREATE OR REPLACE FUNCTION public.refresh_probable_waffle_player_scores_full()
 RETURNS void
 LANGUAGE plpgsql
AS $function$
BEGIN
  REFRESH MATERIALIZED VIEW CONCURRENTLY probable_waffle_player_scores_full;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.upsert_player_score_metric(p_player_score_id bigint, p_metric_key text, p_metric_value bigint)
 RETURNS void
 LANGUAGE plpgsql
AS $function$
DECLARE
  v_metric_type_id int;
BEGIN
  -- Get metric type ID
  SELECT id INTO v_metric_type_id
  FROM probable_waffle_score_metric_types
  WHERE metric_key = p_metric_key;

  IF v_metric_type_id IS NULL THEN
    RAISE EXCEPTION 'Metric type % does not exist', p_metric_key;
  END IF;

  -- Upsert metric value
  INSERT INTO probable_waffle_player_score_metrics (player_score_id, metric_type_id, metric_value)
  VALUES (p_player_score_id, v_metric_type_id, p_metric_value)
  ON CONFLICT (player_score_id, metric_type_id)
    DO UPDATE SET metric_value = EXCLUDED.metric_value;
END;
$function$
;

CREATE UNIQUE INDEX probable_waffle_player_scores_full_id_idx ON public.probable_waffle_player_scores_full USING btree (id);

grant delete on table "public"."fly_squasher_scores" to "anon";

grant insert on table "public"."fly_squasher_scores" to "anon";

grant references on table "public"."fly_squasher_scores" to "anon";

grant select on table "public"."fly_squasher_scores" to "anon";

grant trigger on table "public"."fly_squasher_scores" to "anon";

grant truncate on table "public"."fly_squasher_scores" to "anon";

grant update on table "public"."fly_squasher_scores" to "anon";

grant delete on table "public"."fly_squasher_scores" to "authenticated";

grant insert on table "public"."fly_squasher_scores" to "authenticated";

grant references on table "public"."fly_squasher_scores" to "authenticated";

grant select on table "public"."fly_squasher_scores" to "authenticated";

grant trigger on table "public"."fly_squasher_scores" to "authenticated";

grant truncate on table "public"."fly_squasher_scores" to "authenticated";

grant update on table "public"."fly_squasher_scores" to "authenticated";

grant delete on table "public"."fly_squasher_scores" to "service_role";

grant insert on table "public"."fly_squasher_scores" to "service_role";

grant references on table "public"."fly_squasher_scores" to "service_role";

grant select on table "public"."fly_squasher_scores" to "service_role";

grant trigger on table "public"."fly_squasher_scores" to "service_role";

grant truncate on table "public"."fly_squasher_scores" to "service_role";

grant update on table "public"."fly_squasher_scores" to "service_role";

grant delete on table "public"."little_muncher_scores" to "anon";

grant insert on table "public"."little_muncher_scores" to "anon";

grant references on table "public"."little_muncher_scores" to "anon";

grant select on table "public"."little_muncher_scores" to "anon";

grant trigger on table "public"."little_muncher_scores" to "anon";

grant truncate on table "public"."little_muncher_scores" to "anon";

grant update on table "public"."little_muncher_scores" to "anon";

grant delete on table "public"."little_muncher_scores" to "authenticated";

grant insert on table "public"."little_muncher_scores" to "authenticated";

grant references on table "public"."little_muncher_scores" to "authenticated";

grant select on table "public"."little_muncher_scores" to "authenticated";

grant trigger on table "public"."little_muncher_scores" to "authenticated";

grant truncate on table "public"."little_muncher_scores" to "authenticated";

grant update on table "public"."little_muncher_scores" to "authenticated";

grant delete on table "public"."little_muncher_scores" to "service_role";

grant insert on table "public"."little_muncher_scores" to "service_role";

grant references on table "public"."little_muncher_scores" to "service_role";

grant select on table "public"."little_muncher_scores" to "service_role";

grant trigger on table "public"."little_muncher_scores" to "service_role";

grant truncate on table "public"."little_muncher_scores" to "service_role";

grant update on table "public"."little_muncher_scores" to "service_role";

grant delete on table "public"."messages" to "anon";

grant insert on table "public"."messages" to "anon";

grant references on table "public"."messages" to "anon";

grant select on table "public"."messages" to "anon";

grant trigger on table "public"."messages" to "anon";

grant truncate on table "public"."messages" to "anon";

grant update on table "public"."messages" to "anon";

grant delete on table "public"."messages" to "authenticated";

grant insert on table "public"."messages" to "authenticated";

grant references on table "public"."messages" to "authenticated";

grant select on table "public"."messages" to "authenticated";

grant trigger on table "public"."messages" to "authenticated";

grant truncate on table "public"."messages" to "authenticated";

grant update on table "public"."messages" to "authenticated";

grant delete on table "public"."messages" to "service_role";

grant insert on table "public"."messages" to "service_role";

grant references on table "public"."messages" to "service_role";

grant select on table "public"."messages" to "service_role";

grant trigger on table "public"."messages" to "service_role";

grant truncate on table "public"."messages" to "service_role";

grant update on table "public"."messages" to "service_role";

grant delete on table "public"."probable_waffle_achievements" to "anon";

grant insert on table "public"."probable_waffle_achievements" to "anon";

grant references on table "public"."probable_waffle_achievements" to "anon";

grant select on table "public"."probable_waffle_achievements" to "anon";

grant trigger on table "public"."probable_waffle_achievements" to "anon";

grant truncate on table "public"."probable_waffle_achievements" to "anon";

grant update on table "public"."probable_waffle_achievements" to "anon";

grant delete on table "public"."probable_waffle_achievements" to "authenticated";

grant insert on table "public"."probable_waffle_achievements" to "authenticated";

grant references on table "public"."probable_waffle_achievements" to "authenticated";

grant select on table "public"."probable_waffle_achievements" to "authenticated";

grant trigger on table "public"."probable_waffle_achievements" to "authenticated";

grant truncate on table "public"."probable_waffle_achievements" to "authenticated";

grant update on table "public"."probable_waffle_achievements" to "authenticated";

grant delete on table "public"."probable_waffle_achievements" to "service_role";

grant insert on table "public"."probable_waffle_achievements" to "service_role";

grant references on table "public"."probable_waffle_achievements" to "service_role";

grant select on table "public"."probable_waffle_achievements" to "service_role";

grant trigger on table "public"."probable_waffle_achievements" to "service_role";

grant truncate on table "public"."probable_waffle_achievements" to "service_role";

grant update on table "public"."probable_waffle_achievements" to "service_role";

grant delete on table "public"."probable_waffle_game_sessions" to "anon";

grant insert on table "public"."probable_waffle_game_sessions" to "anon";

grant references on table "public"."probable_waffle_game_sessions" to "anon";

grant select on table "public"."probable_waffle_game_sessions" to "anon";

grant trigger on table "public"."probable_waffle_game_sessions" to "anon";

grant truncate on table "public"."probable_waffle_game_sessions" to "anon";

grant update on table "public"."probable_waffle_game_sessions" to "anon";

grant delete on table "public"."probable_waffle_game_sessions" to "authenticated";

grant insert on table "public"."probable_waffle_game_sessions" to "authenticated";

grant references on table "public"."probable_waffle_game_sessions" to "authenticated";

grant select on table "public"."probable_waffle_game_sessions" to "authenticated";

grant trigger on table "public"."probable_waffle_game_sessions" to "authenticated";

grant truncate on table "public"."probable_waffle_game_sessions" to "authenticated";

grant update on table "public"."probable_waffle_game_sessions" to "authenticated";

grant delete on table "public"."probable_waffle_game_sessions" to "service_role";

grant insert on table "public"."probable_waffle_game_sessions" to "service_role";

grant references on table "public"."probable_waffle_game_sessions" to "service_role";

grant select on table "public"."probable_waffle_game_sessions" to "service_role";

grant trigger on table "public"."probable_waffle_game_sessions" to "service_role";

grant truncate on table "public"."probable_waffle_game_sessions" to "service_role";

grant update on table "public"."probable_waffle_game_sessions" to "service_role";

grant delete on table "public"."probable_waffle_player_score_metrics" to "anon";

grant insert on table "public"."probable_waffle_player_score_metrics" to "anon";

grant references on table "public"."probable_waffle_player_score_metrics" to "anon";

grant select on table "public"."probable_waffle_player_score_metrics" to "anon";

grant trigger on table "public"."probable_waffle_player_score_metrics" to "anon";

grant truncate on table "public"."probable_waffle_player_score_metrics" to "anon";

grant update on table "public"."probable_waffle_player_score_metrics" to "anon";

grant delete on table "public"."probable_waffle_player_score_metrics" to "authenticated";

grant insert on table "public"."probable_waffle_player_score_metrics" to "authenticated";

grant references on table "public"."probable_waffle_player_score_metrics" to "authenticated";

grant select on table "public"."probable_waffle_player_score_metrics" to "authenticated";

grant trigger on table "public"."probable_waffle_player_score_metrics" to "authenticated";

grant truncate on table "public"."probable_waffle_player_score_metrics" to "authenticated";

grant update on table "public"."probable_waffle_player_score_metrics" to "authenticated";

grant delete on table "public"."probable_waffle_player_score_metrics" to "service_role";

grant insert on table "public"."probable_waffle_player_score_metrics" to "service_role";

grant references on table "public"."probable_waffle_player_score_metrics" to "service_role";

grant select on table "public"."probable_waffle_player_score_metrics" to "service_role";

grant trigger on table "public"."probable_waffle_player_score_metrics" to "service_role";

grant truncate on table "public"."probable_waffle_player_score_metrics" to "service_role";

grant update on table "public"."probable_waffle_player_score_metrics" to "service_role";

grant delete on table "public"."probable_waffle_player_scores" to "anon";

grant insert on table "public"."probable_waffle_player_scores" to "anon";

grant references on table "public"."probable_waffle_player_scores" to "anon";

grant select on table "public"."probable_waffle_player_scores" to "anon";

grant trigger on table "public"."probable_waffle_player_scores" to "anon";

grant truncate on table "public"."probable_waffle_player_scores" to "anon";

grant update on table "public"."probable_waffle_player_scores" to "anon";

grant delete on table "public"."probable_waffle_player_scores" to "authenticated";

grant insert on table "public"."probable_waffle_player_scores" to "authenticated";

grant references on table "public"."probable_waffle_player_scores" to "authenticated";

grant select on table "public"."probable_waffle_player_scores" to "authenticated";

grant trigger on table "public"."probable_waffle_player_scores" to "authenticated";

grant truncate on table "public"."probable_waffle_player_scores" to "authenticated";

grant update on table "public"."probable_waffle_player_scores" to "authenticated";

grant delete on table "public"."probable_waffle_player_scores" to "service_role";

grant insert on table "public"."probable_waffle_player_scores" to "service_role";

grant references on table "public"."probable_waffle_player_scores" to "service_role";

grant select on table "public"."probable_waffle_player_scores" to "service_role";

grant trigger on table "public"."probable_waffle_player_scores" to "service_role";

grant truncate on table "public"."probable_waffle_player_scores" to "service_role";

grant update on table "public"."probable_waffle_player_scores" to "service_role";

grant delete on table "public"."probable_waffle_score_metric_types" to "anon";

grant insert on table "public"."probable_waffle_score_metric_types" to "anon";

grant references on table "public"."probable_waffle_score_metric_types" to "anon";

grant select on table "public"."probable_waffle_score_metric_types" to "anon";

grant trigger on table "public"."probable_waffle_score_metric_types" to "anon";

grant truncate on table "public"."probable_waffle_score_metric_types" to "anon";

grant update on table "public"."probable_waffle_score_metric_types" to "anon";

grant delete on table "public"."probable_waffle_score_metric_types" to "authenticated";

grant insert on table "public"."probable_waffle_score_metric_types" to "authenticated";

grant references on table "public"."probable_waffle_score_metric_types" to "authenticated";

grant select on table "public"."probable_waffle_score_metric_types" to "authenticated";

grant trigger on table "public"."probable_waffle_score_metric_types" to "authenticated";

grant truncate on table "public"."probable_waffle_score_metric_types" to "authenticated";

grant update on table "public"."probable_waffle_score_metric_types" to "authenticated";

grant delete on table "public"."probable_waffle_score_metric_types" to "service_role";

grant insert on table "public"."probable_waffle_score_metric_types" to "service_role";

grant references on table "public"."probable_waffle_score_metric_types" to "service_role";

grant select on table "public"."probable_waffle_score_metric_types" to "service_role";

grant trigger on table "public"."probable_waffle_score_metric_types" to "service_role";

grant truncate on table "public"."probable_waffle_score_metric_types" to "service_role";

grant update on table "public"."probable_waffle_score_metric_types" to "service_role";

grant delete on table "public"."probable_waffle_score_snapshots" to "anon";

grant insert on table "public"."probable_waffle_score_snapshots" to "anon";

grant references on table "public"."probable_waffle_score_snapshots" to "anon";

grant select on table "public"."probable_waffle_score_snapshots" to "anon";

grant trigger on table "public"."probable_waffle_score_snapshots" to "anon";

grant truncate on table "public"."probable_waffle_score_snapshots" to "anon";

grant update on table "public"."probable_waffle_score_snapshots" to "anon";

grant delete on table "public"."probable_waffle_score_snapshots" to "authenticated";

grant insert on table "public"."probable_waffle_score_snapshots" to "authenticated";

grant references on table "public"."probable_waffle_score_snapshots" to "authenticated";

grant select on table "public"."probable_waffle_score_snapshots" to "authenticated";

grant trigger on table "public"."probable_waffle_score_snapshots" to "authenticated";

grant truncate on table "public"."probable_waffle_score_snapshots" to "authenticated";

grant update on table "public"."probable_waffle_score_snapshots" to "authenticated";

grant delete on table "public"."probable_waffle_score_snapshots" to "service_role";

grant insert on table "public"."probable_waffle_score_snapshots" to "service_role";

grant references on table "public"."probable_waffle_score_snapshots" to "service_role";

grant select on table "public"."probable_waffle_score_snapshots" to "service_role";

grant trigger on table "public"."probable_waffle_score_snapshots" to "service_role";

grant truncate on table "public"."probable_waffle_score_snapshots" to "service_role";

grant update on table "public"."probable_waffle_score_snapshots" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";


  create policy "Enable read access for all users"
  on "public"."fly_squasher_scores"
  as permissive
  for select
  to public
using (true);



  create policy "Enable write access for authenticated users"
  on "public"."fly_squasher_scores"
  as permissive
  for insert
  to public
with check (((( SELECT auth.uid() AS uid) = user_id) AND (( SELECT auth.role() AS role) = 'user'::text)));



  create policy "Allow insert for authenticated users"
  on "public"."little_muncher_scores"
  as permissive
  for insert
  to authenticated
with check ((user_id = ( SELECT auth.uid() AS uid)));



  create policy "Allow read access for all users"
  on "public"."little_muncher_scores"
  as permissive
  for select
  to public
using (true);



  create policy "Enable insert for service_role only"
  on "public"."messages"
  as permissive
  for insert
  to service_role
with check (true);



  create policy "Enable select for service_role"
  on "public"."messages"
  as permissive
  for select
  to service_role
using (true);



  create policy "Enable select for users based on user_id"
  on "public"."messages"
  as permissive
  for select
  to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable insert access for own achievements"
  on "public"."probable_waffle_achievements"
  as permissive
  for insert
  to public
with check ((( SELECT auth.uid() AS uid) = user_id));



  create policy "Enable read access for all achievements"
  on "public"."probable_waffle_achievements"
  as permissive
  for select
  to public
using (true);



  create policy "Enable insert for service_role only"
  on "public"."probable_waffle_game_sessions"
  as permissive
  for insert
  to service_role
with check (true);



  create policy "Enable select for authenticated users"
  on "public"."probable_waffle_game_sessions"
  as permissive
  for select
  to authenticated
using (((( SELECT auth.uid() AS uid) = created_by_user_id) OR (EXISTS ( SELECT 1
   FROM public.probable_waffle_player_scores ps
  WHERE ((ps.game_session_id = probable_waffle_game_sessions.id) AND (ps.user_id = ( SELECT auth.uid() AS uid)))))));



  create policy "Enable select for service_role"
  on "public"."probable_waffle_game_sessions"
  as permissive
  for select
  to service_role
using (true);



  create policy "Enable update for service_role only"
  on "public"."probable_waffle_game_sessions"
  as permissive
  for update
  to service_role
using (true);



  create policy "Enable insert for service_role only"
  on "public"."probable_waffle_player_score_metrics"
  as permissive
  for insert
  to service_role
with check (true);



  create policy "Enable select for authenticated users"
  on "public"."probable_waffle_player_score_metrics"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM (public.probable_waffle_player_scores ps
     JOIN public.probable_waffle_player_scores other_ps ON (((other_ps.game_session_id = ps.game_session_id) AND (other_ps.user_id = ( SELECT auth.uid() AS uid)))))
  WHERE (ps.id = probable_waffle_player_score_metrics.player_score_id))));



  create policy "Enable select for service_role"
  on "public"."probable_waffle_player_score_metrics"
  as permissive
  for select
  to service_role
using (true);



  create policy "Enable insert for service_role only"
  on "public"."probable_waffle_player_scores"
  as permissive
  for insert
  to service_role
with check (true);



  create policy "Enable select for authenticated users"
  on "public"."probable_waffle_player_scores"
  as permissive
  for select
  to authenticated
using (((user_id = ( SELECT auth.uid() AS uid)) OR (EXISTS ( SELECT 1
   FROM public.probable_waffle_player_scores other_ps
  WHERE ((other_ps.game_session_id = probable_waffle_player_scores.game_session_id) AND (other_ps.user_id = ( SELECT auth.uid() AS uid)))))));



  create policy "Enable select for service_role"
  on "public"."probable_waffle_player_scores"
  as permissive
  for select
  to service_role
using (true);



  create policy "Enable all for service_role"
  on "public"."probable_waffle_score_metric_types"
  as permissive
  for all
  to service_role
using (true);



  create policy "Enable select for authenticated users"
  on "public"."probable_waffle_score_metric_types"
  as permissive
  for select
  to authenticated
using (true);



  create policy "Enable insert for service_role only"
  on "public"."probable_waffle_score_snapshots"
  as permissive
  for insert
  to service_role
with check (true);



  create policy "Enable select for authenticated users"
  on "public"."probable_waffle_score_snapshots"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.probable_waffle_player_scores ps
  WHERE ((ps.game_session_id = probable_waffle_score_snapshots.game_session_id) AND (ps.user_id = ( SELECT auth.uid() AS uid))))));



  create policy "Enable select for service_role"
  on "public"."probable_waffle_score_snapshots"
  as permissive
  for select
  to service_role
using (true);



  create policy "Allow authenticated users to delete their own profile"
  on "public"."profiles"
  as permissive
  for delete
  to public
using ((( SELECT auth.uid() AS uid) = id));



  create policy "Allow authenticated users to select their own profile"
  on "public"."profiles"
  as permissive
  for select
  to public
using ((( SELECT auth.uid() AS uid) = id));



  create policy "Allow authenticated users to update their own profile"
  on "public"."profiles"
  as permissive
  for update
  to public
using ((( SELECT auth.uid() AS uid) = id));


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


  create policy "test bucket access to authenticated users for webp files"
  on "storage"."objects"
  as permissive
  for select
  to public
using (((bucket_id = 'test-bucket'::text) AND (auth.role() = 'authenticated'::text) AND (storage.extension(name) = 'webp'::text)));



