-- Initial schema migration generated from declarative schema files.
-- Source of truth remains supabase/schemas/*.sql.

-- =============================================
-- Source: profiles.sql
-- =============================================

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();
DROP TABLE IF EXISTS public.profiles;

create table public.profiles
(
  id                uuid not null references auth.users on delete cascade,
  name              text,
  profile_image_url text,
  email             text,
  primary key (id)
);

alter table public.profiles
  enable row level security;

-- Create a policy to allow authenticated users to select their own profile
DROP POLICY IF EXISTS "Allow authenticated users to select their own profile" on public.profiles;
CREATE POLICY "Allow authenticated users to select their own profile"
  ON public.profiles
  FOR SELECT
  USING ((select auth.uid()) = id);

-- Create a policy to allow authenticated users to update their own profile
DROP POLICY IF EXISTS "Allow authenticated users to update their own profile" on public.profiles;
CREATE POLICY "Allow authenticated users to update their own profile"
  ON public.profiles
  FOR UPDATE
  USING ((select auth.uid()) = id);

-- Create a policy to allow authenticated users to delete their own profile
DROP POLICY IF EXISTS "Allow authenticated users to delete their own profile" on public.profiles;
CREATE POLICY "Allow authenticated users to delete their own profile"
  ON public.profiles
  FOR DELETE
  USING ((select auth.uid()) = id);

-- inserts a row into public.profiles
CREATE OR REPLACE FUNCTION public.handle_new_user()
  RETURNS trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path = ''
AS
$$
BEGIN

  -- if provider is Google
  IF NEW.raw_app_meta_data ->> 'provider' = 'google' THEN
    INSERT INTO public.profiles (id, email, name, profile_image_url)
    VALUES (NEW.id, NEW.email, NEW.raw_user_meta_data ->> 'name', NEW.raw_user_meta_data ->> 'avatar_url');
  ELSE
    -- else insert random name
    INSERT INTO public.profiles (id, email, name, profile_image_url)
    VALUES (NEW.id,
            NEW.email,
            substring(
              string_agg(chr(65 + floor(random() * 26)::int), ''), -- Random letters (A-Z)
              1, 10 -- 10-character random name
            ),
            '');
  END IF;

  RETURN NEW;
END;
$$;

revoke execute on function public.handle_new_user() from public;
revoke execute on function public.handle_new_user() from anon;
revoke execute on function public.handle_new_user() from authenticated;


-- trigger the function every time a user is created
create trigger on_auth_user_created
  after insert
  on auth.users
  for each row
execute procedure public.handle_new_user();

-- Insert data into public.profiles from auth.users
INSERT INTO public.profiles (id, email, name, profile_image_url)
SELECT id,
       email,
       CASE
         -- If provider is Google, use the name from raw_user_meta_data
         WHEN raw_app_meta_data ->> 'provider' = 'google' THEN raw_user_meta_data ->> 'name'
         -- Otherwise, generate a random name
         ELSE substring(
           string_agg(chr(65 + floor(random() * 26)::int), ''), -- Random letters (A-Z)
           1, 10 -- 10-character random name
              )
         END,
       CASE
         -- If provider is Google, use the avatar_url from raw_user_meta_data
         WHEN raw_app_meta_data ->> 'provider' = 'google' THEN raw_user_meta_data ->> 'avatar_url'
         ELSE '' -- No profile image URL for non-Google users
         END
FROM auth.users
group by id;

revoke all on table public.profiles from anon;
revoke all on table public.profiles from authenticated;

grant select (id, name) on table public.profiles to service_role;

-- =============================================
-- Source: storage.sql
-- =============================================

CREATE POLICY "test bucket access to authenticated users for webp files"
  ON storage.objects FOR SELECT USING (
  -- restrict bucket
  bucket_id = 'test-bucket'
    AND auth.role() = 'authenticated'
    -- allow access to only webp file
    AND storage."extension"(name) = 'webp'
  );

-- =============================================
-- Source: messages.sql
-- =============================================

drop table if exists messages;
create table messages
(
  id               bigint generated by default as identity primary key,
  created_at       timestamp with time zone default now() not null,
  text             text                                   not null,
  user_id          uuid                                   not null,
  game_instance_id uuid                                   null
);

-- add a foreign key constraint to the public.profiles table to improve join performance
alter table messages
  add constraint messages_profile_id_fkey foreign key (user_id) references public.profiles (id);

create index messages_user_id_idx on messages (user_id);

drop policy if exists "Enable read access for all users" on messages;
-- CREATE POLICY "Enable read access for all users" ON "public"."messages"
-- AS PERMISSIVE FOR SELECT
-- TO authenticated
-- USING (true)

drop policy if exists "Enable select for users based on user_id" on messages;
CREATE POLICY "Enable select for users based on user_id" ON "public"."messages"
  AS PERMISSIVE FOR SELECT
  TO authenticated
  USING ((select auth.uid()) = user_id);

drop policy if exists "Enable read access for all users" on messages;
CREATE POLICY "Enable insert for service_role only" ON "public"."messages"
  AS PERMISSIVE FOR INSERT
  TO service_role
  WITH CHECK (true);

drop policy if exists "Enable select for service_role" on messages;
CREATE POLICY "Enable select for service_role" ON "public"."messages"
  AS PERMISSIVE FOR SELECT
  TO service_role
  USING (true);

-- enable row level security
alter table messages
  enable row level security;

revoke all on table public.messages from anon;
revoke all on table public.messages from authenticated;

grant insert, select on table public.messages to service_role;

-- =============================================
-- Source: fly_squasher_scores.sql
-- =============================================

drop table if exists fly_squasher_scores;

CREATE TABLE fly_squasher_scores
(
  id      SERIAL PRIMARY KEY,
  score   INT  NOT NULL,
  level   INT  NOT NULL,
  user_id uuid not null,
  date    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- add a foreign key constraint to the auth.users table
alter table fly_squasher_scores
  add constraint fly_squasher_scores_user_id_fkey foreign key (user_id) references auth.users (id);

drop policy if exists "Enable read access for all users" on fly_squasher_scores;
create policy "Enable read access for all users" on fly_squasher_scores for select using (true);

DROP POLICY IF EXISTS "Enable write access for authenticated users" ON fly_squasher_scores;

CREATE POLICY "Enable write access for authenticated users"
  ON fly_squasher_scores
  FOR INSERT
  WITH CHECK ((select auth.uid()) = user_id AND (select auth.role()) = 'user');

-- enable row level security
alter table fly_squasher_scores
  enable row level security;

create index fly_squasher_scores_user_id_idx
  on fly_squasher_scores (user_id);

-- create a view that joins the fly_squasher_scores table with the auth.users table to get the user's meta data (used full name)
-- and only returns the top 3 unique users' scores for each level (maximum score for each user)
drop view if exists fly_squasher_scores_with_user_meta;
CREATE VIEW fly_squasher_scores_with_user_meta
  with (security_invoker=on)
AS
WITH scores AS (SELECT fss.id,
                       fss.score,
                       fss.level,
                       fss.user_id,
                       fss.date,
                       pr.name,
                       ROW_NUMBER() OVER (PARTITION BY level ORDER BY score DESC) AS level_rn
                FROM (SELECT id,
                             score,
                             level,
                             user_id,
                             date,
                             DENSE_RANK() OVER (PARTITION BY level, user_id ORDER BY score DESC) AS rn
                      FROM fly_squasher_scores) fss
                       JOIN public.profiles pr ON fss.user_id = pr.id
                WHERE fss.rn = 1)
SELECT *
FROM scores
WHERE level_rn <= 3;

revoke all on table public.fly_squasher_scores from anon;
revoke all on table public.fly_squasher_scores from authenticated;
revoke all on table public.fly_squasher_scores_with_user_meta from anon;
revoke all on table public.fly_squasher_scores_with_user_meta from authenticated;
revoke all on sequence public.fly_squasher_scores_id_seq from anon;
revoke all on sequence public.fly_squasher_scores_id_seq from authenticated;

grant insert on table public.fly_squasher_scores to service_role;
grant select (id, score, level, user_id, date) on table public.fly_squasher_scores to service_role;
grant select on table public.fly_squasher_scores_with_user_meta to service_role;
grant usage, select on sequence public.fly_squasher_scores_id_seq to service_role;

-- =============================================
-- Source: probable_waffle_achievements.sql
-- =============================================

drop table if exists probable_waffle_achievements;

CREATE TABLE probable_waffle_achievements
(
  id             SERIAL PRIMARY KEY,
  achievement_id VARCHAR(50) NOT NULL,
  user_id        uuid NOT NULL,
  unlocked_date  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  metadata       JSONB -- Optional metadata about the achievement (e.g., progress data)
);

-- Add a foreign key constraint to the auth.users table
ALTER TABLE probable_waffle_achievements
  ADD CONSTRAINT probable_waffle_achievements_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users (id);

-- Create a unique constraint to prevent duplicate achievements for a user
ALTER TABLE probable_waffle_achievements
  ADD CONSTRAINT probable_waffle_achievements_user_achievement_unique UNIQUE (user_id, achievement_id);

-- Row-level security policies
DROP POLICY IF EXISTS "Enable read access for own achievements" ON probable_waffle_achievements;
CREATE POLICY "Enable read access for all achievements"
  ON probable_waffle_achievements
  FOR SELECT
  USING (true); -- Allow anyone to read any achievement

DROP POLICY IF EXISTS "Enable insert access for authenticated users" ON probable_waffle_achievements;
CREATE POLICY "Enable insert access for own achievements"
  ON probable_waffle_achievements
  FOR INSERT
  WITH CHECK ((select auth.uid()) = user_id); -- Only require user_id match, not specific role

-- Enable row level security
ALTER TABLE probable_waffle_achievements
  ENABLE ROW LEVEL SECURITY;

revoke all on table public.probable_waffle_achievements from anon;
revoke all on table public.probable_waffle_achievements from authenticated;
revoke all on sequence public.probable_waffle_achievements_id_seq from anon;
revoke all on sequence public.probable_waffle_achievements_id_seq from authenticated;

grant insert on table public.probable_waffle_achievements to authenticated;
grant usage on sequence public.probable_waffle_achievements_id_seq to authenticated;

-- =============================================
-- Source: little_muncher_scores.sql
-- =============================================

-- Little Muncher High Scores Table
CREATE TABLE little_muncher_scores (
  id        SERIAL PRIMARY KEY,
  score     INT NOT NULL,
  hill      INT NOT NULL,  -- LittleMuncherHillEnum
  user_id   uuid NOT NULL,
  date      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

-- Row Level Security
ALTER TABLE little_muncher_scores ENABLE ROW LEVEL SECURITY;

-- Policy: Allow anyone to read scores
CREATE POLICY "Allow read access for all users"
  ON little_muncher_scores FOR SELECT USING (true);

-- Policy: Allow authenticated users to insert their own scores
DROP POLICY IF EXISTS "Allow insert for authenticated users" ON little_muncher_scores;
CREATE POLICY "Allow insert for authenticated users"
  ON little_muncher_scores FOR INSERT TO authenticated
  WITH CHECK (user_id = (select auth.uid()));

create index little_muncher_scores_user_id_idx
  on little_muncher_scores (user_id);

-- View: Top 3 unique users per hill (highest score per user)
DROP VIEW IF EXISTS little_muncher_scores_with_user_meta;
CREATE VIEW little_muncher_scores_with_user_meta
  with (security_invoker=on)
AS
WITH ranked_scores AS (
  SELECT
    s.id,
    s.score,
    s.hill,
    s.user_id,
    s.date,
    p.name AS user_name,
    ROW_NUMBER() OVER (PARTITION BY s.hill, s.user_id ORDER BY s.score DESC) as user_rn
  FROM little_muncher_scores s
  JOIN profiles p ON s.user_id = p.id
),
unique_user_scores AS (
  SELECT * FROM ranked_scores WHERE user_rn = 1
),
hill_ranked AS (
  SELECT
    id,
    score,
    hill,
    user_id,
    user_name,
    date,
    ROW_NUMBER() OVER (PARTITION BY hill ORDER BY score DESC) as hill_rn
  FROM unique_user_scores
)
SELECT id, score, hill, user_id, user_name, date
FROM hill_ranked
WHERE hill_rn <= 3
ORDER BY hill, hill_rn;

revoke all on table public.little_muncher_scores from anon;
revoke all on table public.little_muncher_scores from authenticated;
revoke all on table public.little_muncher_scores_with_user_meta from anon;
revoke all on table public.little_muncher_scores_with_user_meta from authenticated;
revoke all on sequence public.little_muncher_scores_id_seq from anon;
revoke all on sequence public.little_muncher_scores_id_seq from authenticated;

grant insert on table public.little_muncher_scores to service_role;
grant select on table public.little_muncher_scores_with_user_meta to service_role;
grant usage, select on sequence public.little_muncher_scores_id_seq to service_role;

-- =============================================
-- Source: probable_waffle_game_sessions.sql
-- =============================================

-- =============================================================================
-- Probable Waffle Game Sessions
-- =============================================================================
-- Tracks game sessions (online and offline) for score submission and match history.
--
-- Key fields:
--   scores_submitted    - set to true when the last human player submits all scores
--   scores_submitted_by - UUID of the player who submitted (idempotency tracking)
--   human_player_count  - used by clients to determine who is "last" to submit
--   session_state       - InProgress → ToScoreScreen → Completed / Abandoned
--
-- Multiplayer score submission strategy:
--   Only the last human player to reach the score screen submits scores.
--   API is idempotent: duplicate submissions return success without inserting again.
--
-- Depends on: profiles.sql, messages.sql (messages FK added here)
-- =============================================================================

drop table if exists probable_waffle_game_sessions cascade;

create table probable_waffle_game_sessions
(
  id                      uuid primary key default gen_random_uuid(),
  game_instance_id        uuid                     not null unique,
  game_type               text                     not null,
  map_id                  int                      not null,
  session_state           text                     not null,
  started_at              timestamp with time zone default now() not null,
  ended_at                timestamp with time zone null,
  total_duration_seconds  int                      null,
  created_by_user_id      uuid                     not null,
  scores_submitted        boolean                  not null default false,
  scores_submitted_by     uuid                     null,
  scores_submitted_at     timestamp with time zone null,
  human_player_count      int                      not null default 1,
  created_at              timestamp with time zone default now() not null
);

-- add foreign key constraint to the profiles table
alter table probable_waffle_game_sessions
  add constraint probable_waffle_game_sessions_created_by_user_id_fkey
  foreign key (created_by_user_id) references public.profiles (id);

-- add foreign key constraint for scores_submitted_by
alter table probable_waffle_game_sessions
  add constraint probable_waffle_game_sessions_scores_submitted_by_fkey
  foreign key (scores_submitted_by) references public.profiles (id);

create index probable_waffle_game_sessions_scores_submitted_by_idx
  on probable_waffle_game_sessions (scores_submitted_by)
  where scores_submitted_by is not null;

create index probable_waffle_game_sessions_created_by_user_id_idx
  on probable_waffle_game_sessions (created_by_user_id);

-- RLS policies
drop policy if exists "Enable insert for service_role only" on probable_waffle_game_sessions;
create policy "Enable insert for service_role only" on probable_waffle_game_sessions
  as permissive for insert
  to service_role
  with check (true);

drop policy if exists "Enable update for service_role only" on probable_waffle_game_sessions;
create policy "Enable update for service_role only" on probable_waffle_game_sessions
  as permissive for update
  to service_role
  using (true);

drop policy if exists "Enable select for service_role" on probable_waffle_game_sessions;
create policy "Enable select for service_role" on probable_waffle_game_sessions
  as permissive for select
  to service_role
  using (true);

-- enable row level security
alter table probable_waffle_game_sessions
  enable row level security;

-- messages
-- add foreign key constraint to game sessions table
-- Note: This constraint requires probable_waffle_game_sessions table to exist first.
alter table messages
  add constraint messages_game_instance_id_fkey
    foreign key (game_instance_id) references probable_waffle_game_sessions (game_instance_id) on delete set null;

-- add comment explaining the relationship
comment on column messages.game_instance_id is 'References the game instance UUID from probable_waffle_game_sessions';

revoke all on table public.probable_waffle_game_sessions from anon;
revoke all on table public.probable_waffle_game_sessions from authenticated;

grant select, insert, update on table public.probable_waffle_game_sessions to service_role;



-- =============================================
-- Source: probable_waffle_player_scores.sql
-- =============================================

-- =============================================================================
-- Probable Waffle Player Scores (Hybrid EAV Design)
-- =============================================================================
-- Stores per-player statistics for completed game sessions.
-- Uses a 3-table hybrid design (core fields + EAV metrics catalog + metric values).
--
-- Tables:
--   probable_waffle_player_scores        - core player info (result, score, faction…)
--   probable_waffle_score_metric_types   - metric catalog; add new metrics with INSERT only
--   probable_waffle_player_score_metrics - EAV values; only non-zero metrics stored
--
-- Materialized view (probable_waffle_player_scores_full):
--   Pivots EAV rows into columns for fast score-screen and history queries.
--   Refresh after bulk inserts: SELECT refresh_probable_waffle_player_scores_full();
--
-- Helper functions:
--   get_player_score_metrics(player_score_id)             → JSONB of all metrics
--   upsert_player_score_metric(id, metric_key, value)     → insert or update one metric
--
-- Stats view (probable_waffle_player_stats):
--   Aggregates per-user wins/losses/averages from the materialized view.
--
-- Depends on: probable_waffle_game_sessions.sql
-- =============================================================================

-- Create player scores table with hybrid design
-- Core metrics in main table, extended metrics in separate table for flexibility
drop table if exists probable_waffle_player_scores cascade;
drop table if exists probable_waffle_player_score_metrics cascade;
drop table if exists probable_waffle_score_metric_types cascade;

-- Main player scores table - contains only core/common fields
create table probable_waffle_player_scores
(
  id                    bigserial primary key,
  game_session_id       uuid                     not null,
  user_id               uuid                     null,
  player_number         int                      not null,
  player_name           text                     not null,
  player_type           text                     not null,
  team_number           int                      null,
  faction_type          text                     not null,
  game_result           text                     not null,
  eliminated            boolean                  not null default false,
  eliminated_at         timestamp with time zone null,
  final_score           int                      not null default 0,
  created_at            timestamp with time zone default now() not null
);

-- Metric types catalog - defines what metrics can be tracked
create table probable_waffle_score_metric_types
(
  id                    serial primary key,
  metric_key            text                     not null unique,
  metric_name           text                     not null,
  metric_category       text                     not null, -- 'units', 'buildings', 'resources', 'combat', 'economy'
  description           text                     null,
  display_order         int                      not null default 0,
  is_active             boolean                  not null default true,
  created_at            timestamp with time zone default now() not null
);

-- Individual metric values - flexible EAV pattern for extended metrics
create table probable_waffle_player_score_metrics
(
  id                    bigserial primary key,
  player_score_id       bigint                   not null,
  metric_type_id        int                      not null,
  metric_value          bigint                   not null default 0,
  created_at            timestamp with time zone default now() not null
);

-- Foreign key constraints
alter table probable_waffle_player_scores
  add constraint probable_waffle_player_scores_game_session_id_fkey
  foreign key (game_session_id) references probable_waffle_game_sessions (id) on delete cascade;

alter table probable_waffle_player_scores
  add constraint probable_waffle_player_scores_user_id_fkey
  foreign key (user_id) references public.profiles (id);

alter table probable_waffle_player_score_metrics
  add constraint probable_waffle_player_score_metrics_player_score_id_fkey
  foreign key (player_score_id) references probable_waffle_player_scores (id) on delete cascade;

alter table probable_waffle_player_score_metrics
  add constraint probable_waffle_player_score_metrics_metric_type_id_fkey
  foreign key (metric_type_id) references probable_waffle_score_metric_types (id);

-- Indexes on main table
create index probable_waffle_player_scores_user_id_idx
  on probable_waffle_player_scores (user_id)
  where user_id is not null;

create unique index probable_waffle_player_scores_session_player_idx
  on probable_waffle_player_scores (game_session_id, player_number);

-- Indexes on metrics table
create index probable_waffle_player_score_metrics_metric_type_id_idx
  on probable_waffle_player_score_metrics (metric_type_id);

-- Unique constraint: one value per metric per player score
create unique index probable_waffle_player_score_metrics_unique_idx
  on probable_waffle_player_score_metrics (player_score_id, metric_type_id);

-- RLS policies for main scores table
drop policy if exists "Enable insert for service_role only" on probable_waffle_player_scores;
create policy "Enable insert for service_role only" on probable_waffle_player_scores
  as permissive for insert
  to service_role
  with check (true);

drop policy if exists "Enable select for authenticated users" on probable_waffle_player_scores;
create policy "Enable select for authenticated users" on probable_waffle_player_scores
  as permissive for select
  to authenticated
  using (
    user_id = (select auth.uid())
    or exists (
      select 1
      from probable_waffle_player_scores other_ps
      where other_ps.game_session_id = probable_waffle_player_scores.game_session_id
        and other_ps.user_id = (select auth.uid())
    )
  );

drop policy if exists "Enable select for service_role" on probable_waffle_player_scores;
create policy "Enable select for service_role" on probable_waffle_player_scores
  as permissive for select
  to service_role
  using (true);

alter table probable_waffle_player_scores
  enable row level security;

-- RLS policies for metrics table
drop policy if exists "Enable insert for service_role only" on probable_waffle_player_score_metrics;
create policy "Enable insert for service_role only" on probable_waffle_player_score_metrics
  as permissive for insert
  to service_role
  with check (true);

drop policy if exists "Enable select for authenticated users" on probable_waffle_player_score_metrics;
create policy "Enable select for authenticated users" on probable_waffle_player_score_metrics
  as permissive for select
  to authenticated
  using (
    exists (
      select 1
      from probable_waffle_player_scores ps
      join probable_waffle_player_scores other_ps
        on other_ps.game_session_id = ps.game_session_id
           and other_ps.user_id = (select auth.uid())
      where ps.id = probable_waffle_player_score_metrics.player_score_id
    )
  );

drop policy if exists "Enable select for service_role" on probable_waffle_player_score_metrics;
create policy "Enable select for service_role" on probable_waffle_player_score_metrics
  as permissive for select
  to service_role
  using (true);

alter table probable_waffle_player_score_metrics
  enable row level security;

-- RLS policies for metric types table (read-only for all authenticated users)
drop policy if exists "Enable select for authenticated users" on probable_waffle_score_metric_types;
create policy "Enable select for authenticated users" on probable_waffle_score_metric_types
  as permissive for select
  to authenticated
  using (true);

drop policy if exists "Enable all for service_role" on probable_waffle_score_metric_types;
create policy "Enable all for service_role" on probable_waffle_score_metric_types
  as permissive for all
  to service_role
  using (true);

alter table probable_waffle_score_metric_types
  enable row level security;

-- Backfill game session access policy now that player scores exist
drop policy if exists "Enable select for authenticated users" on probable_waffle_game_sessions;
create policy "Enable select for authenticated users" on probable_waffle_game_sessions
  as permissive for select
  to authenticated
  using (
    (select auth.uid()) = created_by_user_id
    or exists (
      select 1
      from probable_waffle_player_scores ps
      where ps.game_session_id = probable_waffle_game_sessions.id
        and ps.user_id = (select auth.uid())
    )
  );

-- Match history view depends on both sessions and player scores
drop view if exists probable_waffle_match_history;
create view probable_waffle_match_history
  with (security_invoker=on)
as
select
  gs.id,
  gs.game_instance_id,
  gs.game_type,
  gs.map_id,
  gs.session_state,
  gs.started_at,
  gs.ended_at,
  gs.total_duration_seconds,
  gs.scores_submitted,
  gs.human_player_count,
  creator.name as created_by_name,
  submitter.name as submitted_by_name,
  (
    select json_agg(
      json_build_object(
        'player_number', ps.player_number,
        'player_name', ps.player_name,
        'player_type', ps.player_type,
        'faction_type', ps.faction_type,
        'game_result', ps.game_result,
        'final_score', ps.final_score,
        'is_current_user', ps.user_id = auth.uid()
      )
      order by ps.final_score desc
    )
    from probable_waffle_player_scores ps
    where ps.game_session_id = gs.id
  ) as players,
  exists(
    select 1
    from probable_waffle_player_scores ps
    where ps.game_session_id = gs.id
      and ps.user_id = auth.uid()
  ) as user_participated,
  (
    select ps.game_result
    from probable_waffle_player_scores ps
    where ps.game_session_id = gs.id
      and ps.user_id = auth.uid()
    limit 1
  ) as user_result
from probable_waffle_game_sessions gs
left join public.profiles creator on gs.created_by_user_id = creator.id
left join public.profiles submitter on gs.scores_submitted_by = submitter.id
where gs.scores_submitted = true
  and exists(
    select 1
    from probable_waffle_player_scores ps
    where ps.game_session_id = gs.id
      and ps.user_id = auth.uid()
  )
order by gs.ended_at desc nulls last, gs.started_at desc;

-- Insert predefined metric types
insert into probable_waffle_score_metric_types (metric_key, metric_name, metric_category, description, display_order) values
-- Units category
('units_produced', 'Units Produced', 'units', 'Total number of units created', 1),
('units_killed', 'Units Killed', 'units', 'Total enemy units destroyed', 2),
('units_lost', 'Units Lost', 'units', 'Total own units lost', 3),

-- Buildings category
('buildings_constructed', 'Buildings Constructed', 'buildings', 'Total buildings completed', 11),
('buildings_destroyed', 'Buildings Destroyed', 'buildings', 'Total enemy buildings destroyed', 12),
('buildings_lost', 'Buildings Lost', 'buildings', 'Total own buildings lost', 13),

-- Resources category
('resources_collected_minerals', 'Minerals Collected', 'resources', 'Total minerals gathered', 21),
('resources_collected_stone', 'Stone Collected', 'resources', 'Total stone gathered', 22),
('resources_collected_wood', 'Wood Collected', 'resources', 'Total wood gathered', 23),
('resources_spent_minerals', 'Minerals Spent', 'resources', 'Total minerals used', 24),
('resources_spent_stone', 'Stone Spent', 'resources', 'Total stone used', 25),
('resources_spent_wood', 'Wood Spent', 'resources', 'Total wood used', 26),
('final_resources_minerals', 'Final Minerals', 'resources', 'Minerals remaining at end', 27),
('final_resources_stone', 'Final Stone', 'resources', 'Stone remaining at end', 28),
('final_resources_wood', 'Final Wood', 'resources', 'Wood remaining at end', 29),

-- Combat category
('damage_dealt', 'Damage Dealt', 'combat', 'Total damage inflicted', 31),
('damage_received', 'Damage Received', 'combat', 'Total damage taken', 32),
('healing_done', 'Healing Done', 'combat', 'Total healing provided', 33),

-- Economy category
('max_army_size', 'Max Army Size', 'economy', 'Peak unit count achieved', 41),
('max_building_count', 'Max Building Count', 'economy', 'Peak building count achieved', 42);

-- Create materialized view for efficient querying with all metrics pivoted
drop materialized view if exists probable_waffle_player_scores_full;
create materialized view probable_waffle_player_scores_full as
select
  ps.id,
  ps.game_session_id,
  ps.user_id,
  ps.player_number,
  ps.player_name,
  ps.player_type,
  ps.team_number,
  ps.faction_type,
  ps.game_result,
  ps.eliminated,
  ps.eliminated_at,
  ps.final_score,
  ps.created_at,
  -- Pivot metrics into columns
  max(case when mt.metric_key = 'units_produced' then m.metric_value else 0 end) as units_produced,
  max(case when mt.metric_key = 'units_killed' then m.metric_value else 0 end) as units_killed,
  max(case when mt.metric_key = 'units_lost' then m.metric_value else 0 end) as units_lost,
  max(case when mt.metric_key = 'buildings_constructed' then m.metric_value else 0 end) as buildings_constructed,
  max(case when mt.metric_key = 'buildings_destroyed' then m.metric_value else 0 end) as buildings_destroyed,
  max(case when mt.metric_key = 'buildings_lost' then m.metric_value else 0 end) as buildings_lost,
  max(case when mt.metric_key = 'resources_collected_minerals' then m.metric_value else 0 end) as resources_collected_minerals,
  max(case when mt.metric_key = 'resources_collected_stone' then m.metric_value else 0 end) as resources_collected_stone,
  max(case when mt.metric_key = 'resources_collected_wood' then m.metric_value else 0 end) as resources_collected_wood,
  max(case when mt.metric_key = 'resources_spent_minerals' then m.metric_value else 0 end) as resources_spent_minerals,
  max(case when mt.metric_key = 'resources_spent_stone' then m.metric_value else 0 end) as resources_spent_stone,
  max(case when mt.metric_key = 'resources_spent_wood' then m.metric_value else 0 end) as resources_spent_wood,
  max(case when mt.metric_key = 'final_resources_minerals' then m.metric_value else 0 end) as final_resources_minerals,
  max(case when mt.metric_key = 'final_resources_stone' then m.metric_value else 0 end) as final_resources_stone,
  max(case when mt.metric_key = 'final_resources_wood' then m.metric_value else 0 end) as final_resources_wood,
  max(case when mt.metric_key = 'damage_dealt' then m.metric_value else 0 end) as damage_dealt,
  max(case when mt.metric_key = 'damage_received' then m.metric_value else 0 end) as damage_received,
  max(case when mt.metric_key = 'healing_done' then m.metric_value else 0 end) as healing_done,
  max(case when mt.metric_key = 'max_army_size' then m.metric_value else 0 end) as max_army_size,
  max(case when mt.metric_key = 'max_building_count' then m.metric_value else 0 end) as max_building_count
from probable_waffle_player_scores ps
left join probable_waffle_player_score_metrics m on ps.id = m.player_score_id
left join probable_waffle_score_metric_types mt on m.metric_type_id = mt.id
group by ps.id, ps.game_session_id, ps.user_id, ps.player_number, ps.player_name,
         ps.player_type, ps.team_number, ps.faction_type, ps.game_result,
         ps.eliminated, ps.eliminated_at, ps.final_score, ps.created_at;

-- Index on materialized view
create unique index probable_waffle_player_scores_full_id_idx on probable_waffle_player_scores_full (id);

revoke all on table public.probable_waffle_player_scores_full from public;
revoke all on table public.probable_waffle_player_scores_full from anon;
revoke all on table public.probable_waffle_player_scores_full from authenticated;

-- Create view for player statistics aggregation (uses materialized view for performance)
drop view if exists probable_waffle_player_stats;
create view probable_waffle_player_stats
  with (security_invoker=on)
as
select
  ps.user_id,
  p.name as player_name,
  count(*) as total_games,
  count(*) filter (where ps.game_result = 'win') as wins,
  count(*) filter (where ps.game_result = 'loss') as losses,
  count(*) filter (where ps.game_result = 'tie') as ties,
  round(
    (count(*) filter (where ps.game_result = 'win')::decimal /
     nullif(count(*) filter (where ps.game_result != 'quit'), 0)) * 100,
    2
  ) as win_rate_percentage,
  sum(ps.units_produced) as total_units_produced,
  sum(ps.units_killed) as total_units_killed,
  sum(ps.buildings_constructed) as total_buildings_constructed,
  sum(ps.buildings_destroyed) as total_buildings_destroyed,
  avg(ps.final_score)::int as avg_final_score,
  max(ps.final_score) as max_final_score
from probable_waffle_player_scores_full ps
left join public.profiles p on ps.user_id = p.id
where ps.user_id is not null
group by ps.user_id, p.name;

-- 1. Refresh Function
CREATE OR REPLACE FUNCTION refresh_probable_waffle_player_scores_full()
  RETURNS void
  LANGUAGE plpgsql
  SET search_path = public, pg_temp
AS $$
BEGIN
  REFRESH MATERIALIZED VIEW CONCURRENTLY probable_waffle_player_scores_full;
END;
$$;

revoke all on table public.probable_waffle_player_scores from anon;
revoke all on table public.probable_waffle_player_scores from authenticated;
revoke all on table public.probable_waffle_score_metric_types from anon;
revoke all on table public.probable_waffle_score_metric_types from authenticated;
revoke all on table public.probable_waffle_player_score_metrics from anon;
revoke all on table public.probable_waffle_player_score_metrics from authenticated;
revoke all on table public.probable_waffle_match_history from anon;
revoke all on table public.probable_waffle_match_history from authenticated;
revoke all on table public.probable_waffle_player_stats from anon;
revoke all on table public.probable_waffle_player_stats from authenticated;
revoke all on sequence public.probable_waffle_player_scores_id_seq from anon;
revoke all on sequence public.probable_waffle_player_scores_id_seq from authenticated;
revoke all on sequence public.probable_waffle_player_score_metrics_id_seq from anon;
revoke all on sequence public.probable_waffle_player_score_metrics_id_seq from authenticated;

grant select, insert on table public.probable_waffle_player_scores to service_role;
grant select on table public.probable_waffle_score_metric_types to service_role;
grant select, insert on table public.probable_waffle_player_score_metrics to service_role;
grant select on table public.probable_waffle_player_scores_full to service_role;
grant execute on function public.refresh_probable_waffle_player_scores_full() to service_role;
grant usage, select on sequence public.probable_waffle_player_scores_id_seq to service_role;
grant usage, select on sequence public.probable_waffle_player_score_metrics_id_seq to service_role;

-- 2. Get Metrics Helper
CREATE OR REPLACE FUNCTION get_player_score_metrics(p_player_score_id bigint)
  RETURNS jsonb
  LANGUAGE sql
  STABLE
  SET search_path = public, pg_temp
AS $$
SELECT jsonb_object_agg(mt.metric_key, m.metric_value)
FROM probable_waffle_player_score_metrics m
       JOIN probable_waffle_score_metric_types mt ON m.metric_type_id = mt.id
WHERE m.player_score_id = p_player_score_id;
$$;

-- 3. Upsert Metric Helper
CREATE OR REPLACE FUNCTION upsert_player_score_metric(
  p_player_score_id bigint,
  p_metric_key text,
  p_metric_value bigint
)
  RETURNS void
  LANGUAGE plpgsql
  SET search_path = public, pg_temp
AS $$
DECLARE
  v_metric_type_id int;
BEGIN
  -- Get metric type ID
  SELECT id INTO v_metric_type_id
  FROM probable_waffle_score_metric_types
  WHERE metric_key = p_metric_key;

  IF v_metric_type_id IS NULL THEN
    RAISE EXCEPTION 'Metric type % does not exist', p_metric_key;
  END IF;

  -- Upsert metric value
  INSERT INTO probable_waffle_player_score_metrics (player_score_id, metric_type_id, metric_value)
  VALUES (p_player_score_id, v_metric_type_id, p_metric_value)
  ON CONFLICT (player_score_id, metric_type_id)
    DO UPDATE SET metric_value = EXCLUDED.metric_value;
END;
$$;


-- =============================================
-- Source: probable_waffle_score_snapshots.sql
-- =============================================

-- Score snapshots for timeline charts in match history
drop table if exists probable_waffle_score_snapshots cascade;

create table probable_waffle_score_snapshots
(
  id              bigserial primary key,
  game_session_id uuid                     not null,
  snapshots       jsonb                    not null, -- Array of {timestamp_ms, playerScores[]}
  created_at      timestamp with time zone default now() not null
);

alter table probable_waffle_score_snapshots
  add constraint probable_waffle_score_snapshots_game_session_id_fkey
  foreign key (game_session_id) references probable_waffle_game_sessions (id) on delete cascade;

create unique index probable_waffle_score_snapshots_game_session_id_idx
  on probable_waffle_score_snapshots (game_session_id);

-- RLS: only service_role may insert; authenticated users may read
drop policy if exists "Enable insert for service_role only" on probable_waffle_score_snapshots;
create policy "Enable insert for service_role only" on probable_waffle_score_snapshots
  as permissive for insert
  to service_role
  with check (true);

drop policy if exists "Enable select for authenticated users" on probable_waffle_score_snapshots;
create policy "Enable select for authenticated users" on probable_waffle_score_snapshots
  as permissive for select
  to authenticated
  using (
    exists (
      select 1
      from probable_waffle_player_scores ps
      where ps.game_session_id = probable_waffle_score_snapshots.game_session_id
        and ps.user_id = (select auth.uid())
    )
  );

drop policy if exists "Enable select for service_role" on probable_waffle_score_snapshots;
create policy "Enable select for service_role" on probable_waffle_score_snapshots
  as permissive for select
  to service_role
  using (true);

alter table probable_waffle_score_snapshots
  enable row level security;

revoke all on table public.probable_waffle_score_snapshots from anon;
revoke all on table public.probable_waffle_score_snapshots from authenticated;
revoke all on sequence public.probable_waffle_score_snapshots_id_seq from anon;
revoke all on sequence public.probable_waffle_score_snapshots_id_seq from authenticated;

grant select, insert on table public.probable_waffle_score_snapshots to service_role;
grant usage, select on sequence public.probable_waffle_score_snapshots_id_seq to service_role;

