export const slovenianBadWords = [
  'bes te plentaj',
  'bingala bongala',
  'bog te nima rad',
  'cepec',
  'da bi te koklja brcnila',
  'drek',
  'drekec pekec',
  'drkati',
  'frdaman',
  'fuk',
  'holtnahamol',
  'hop cefizelj',
  'hudič',
  'hudičevka',
  'iti v maloro',
  'jeba',
  'jebat ga',
  'Jebela cesta',
  'jebemti mater kosmato',
  'jebemti uha',
  'jebo ti pas mater kad te napravio',
  'jejtena',
  'ježešna',
  'klinc te gleda',
  'ko ga šiša',
  'konjski kurac',
  'kot da bi konj v senco rital',
  'Krucefiks',
  'krucinalbanda',
  'krščen duš',
  'kuga salamenska',
  'kurac',
  'kurac palac',
  'kurenk',
  'madona',
  'mandi mandi',
  'mater',
  'mašinca',
  'moj bog',
  'naj te strela udari',
  'ne biti vreden počenega groša',
  'ne jebati',
  'obrisati si šobe',
  'pejd u tri pirovske',
  'pejt v rit',
  'pismo',
  'pizda',
  'pišuka',
  'pička',
  'pička ti materina',
  'pičkin dim',
  'pičkuračku',
  'poslati v kurilnico',
  'poslati v picerijo',
  'poslati v pisarno',
  'pribijati',
  'prmejdun',
  'tri krasne',
  'vrag te pocitraj',
  'čka',
  'čri čri',
  'aškrc',
  'bes te plentaj',
  'bingala bongala',
  'bog te nima rad',
  'cepec',
  'da bi te koklja brcnila',
  'da bi te pes povohal',
  'drek',
  'drekec pekec',
  'drkati',
  'fakof',
  'fekalc',
  'frdaman',
  'fuk',
  'holtnahamol',
  'hop cefizelj',
  'hudič',
  'hudičevka',
  'hvala za rože',
  'iti na š',
  'iti v maloro',
  'jeba',
  'jebat ga',
  'Jebela cesta',
  'jebemti mater kosmato',
  'jebemti uha',
  'jebi ga - original',
  'jebo ti pas mater kad te napravio',
  'jejtena',
  'ježešna',
  'joj prejoj',
  'klinc te gleda',
  'ko ga šiša',
  'ko jebe Bosance',
  'konjski kurac',
  'kot da bi konj v senco rital',
  'krizus',
  'Krucefiks',
  'krucinalbanda',
  'krščen duš',
  'krščen matiček',
  'kuga salamenska',
  'kurac',
  'kurac palac',
  'kurenk',
  'madona',
  'mandi mandi',
  'mater',
  'mašinca',
  'mička',
  'moj bog',
  'naj te strela udari',
  'ne biti vreden počenega groša',
  'ne jebati',
  'obrisati si šobe',
  'Ojdip',
  'orkadibigoli',
  'pejd u tri pirovske',
  'pejt v rit',
  'pismo',
  'pizda',
  'Pizda mi greš na kurac tip mona ej',
  'pizda na robu gozda',
  'pišuka',
  'pička',
  'pička ti materina',
  'pička ti žlička',
  'pičkin dim',
  'Pičkopeja',
  'pičkuračku',
  'pojdi v pisarno',
  'porkadindijo',
  'poslati v kurilnico',
  'poslati v picerijo',
  'poslati v pisarno',
  'preklezakurnk',
  'Preklinc',
  'pribijati',
  'primaruha',
  'prmejdun',
  'ps ti brado lizu',
  'Svija',
  'tri krasne',
  'vrag te pocitraj',
  'Vragu na roge',
  'včeraj sem juho jedel',
  'za poflancat',
  'zajebati',
  'šajeta te hitla u laštrigo od bandant',
  'čka',
  'čkapi',
  'čri čri',
  'bes te plentaj',
  'bingala bongala',
  'bog te nima rad',
  'cepec',
  'da bi te koklja brcnila',
  'drek',
  'drekec pekec',
  'frdaman',
  'fuk',
  'holtnahamol',
  'hop cefizelj',
  'hudič',
  'hudičevka',
  'iti v maloro',
  'jebat ga',
  'jebemti mater kosmato',
  'jebo ti pas mater kad te napravio',
  'jejtena',
  'ježešna',
  'klinc te gleda',
  'ko ga šiša',
  'konjski kurac',
  'kot da bi konj v senco rital',
  'Krucefiks',
  'krucinalbanda',
  'krščen duš',
  'kuga salamenska',
  'kurac palac',
  'madona',
  'mandi mandi',
  'mater',
  'mašinca',
  'moj bog',
  'naj te strela udari',
  'ne biti vreden počenega groša',
  'ne jebati',
  'obrisati si šobe',
  'pejt v rit',
  'pismo',
  'pizda',
  'pišuka',
  'pička',
  'pička ti materina',
  'pičkuračku',
  'poslati v kurilnico',
  'poslati v picerijo',
  'poslati v pisarno',
  'Preklinc',
  'pribijati',
  'prmejdun',
  'tri krasne',
  'čka',
  'tristo kosmatih medvedov'
];
