name: CI Branches

on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - ready_for_review
      - synchronize
      - reopened

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 23 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
        #   fetch-depth: 50

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linter
        run: pnpm run lint
        env:
          NX_BRANCH: ${{ github.event.number }}
          NX_RUN_GROUP: ${{ github.run_id }}

      - name: Run tests
        run: pnpm run test
        env:
          NX_BRANCH: ${{ github.event.number }}
          NX_RUN_GROUP: ${{ github.run_id }}

      - name: Build Packages
        run: pnpm run build-gh-pages
        env:
          NX_BRANCH: ${{ github.event.number }}
          NX_RUN_GROUP: ${{ github.run_id }}
