name: CI Branches

on:
  pull_request:
    branches:
      - main
      - develop

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 23 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # with:
        #   fetch-depth: 50

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run linter
        run: pnpm run lint
        env:
          NX_BRANCH: ${{ github.event.number }}
          NX_RUN_GROUP: ${{ github.run_id }}

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run tests
        run: pnpm run test
        env:
          NX_BRANCH: ${{ github.event.number }}
          NX_RUN_GROUP: ${{ github.run_id }}

  build-packages:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Build Packages
        run: pnpm run build-gh-pages
        env:
          NX_BRANCH: ${{ github.event.number }}
          NX_RUN_GROUP: ${{ github.run_id }}
